version = 0.1

[default.deploy.parameters]
stack_name = "eventro-aws-backend"
resolve_s3 = true
s3_prefix = "eventro-aws-backend"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "ap-south-1"
